config/routes.rb
Rails.application.routes.draw do
  resources :students, shallow: true do
    resources :addresses
  end

  resources :courses, only: [:show]
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description, :street, :city, :state, :zip_code
  
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates_presence_of :title

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name

  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    student = Student.find(params[:student_id])
    student.addresses.create(address_params)
    redirect_to student_path(student)
  end

  private

  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zip_code, :student_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    redirect_to student_path(student)
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.find(params[:id])
    student.update(student_params)
    redirect_to student_path(student)
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<%= form_for [@student, @address] do |f| %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.label :street %>
<%= f.text_area :street %>

<%= f.label :city %>
<%= f.text_area :city %>

<%= f.label :state %>
<%= f.text_area :state %>

<%= f.label :zip_code %>
<%= f.text_field :zip_code %>

<%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<%= @course.title %>
<% @course.students.each do |student| %>
<%= student.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enrollment</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <nav id='navigation'>
    <%= link_to 'See All Students', students_path  %>
    <%= link_to 'Create a Student', new_student_path  %>
  </nav>
  <%= yield %>
</body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>

<%= f.label :name %>
<%= f.text_area :name %>

<%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>
<% @students.each do |student| %>
<div id="student-<%= student.id %>">
  <p>Name: <%= student.name %></p>
  <%= link_to 'Delete', student_path(student), method: 'delete' %>
</div>
<% end %>

app/views/students/new.html.erb
<%= form_for @student do |f| %>

<%= f.label :name %>
<%= f.text_area :name %>

<%= f.submit %>
<% end %>

app/views/students/show.html.erb
<p>Name: <%= @student.name %></p>
<%= @student.addresses.each do |address| %>
<p>Description: <%= address.description %></p>
<p>Street: <%= address.street %></p>
<p>City: <%= address.city %></p>
<p>State: <%= address.state %></p>
<p>Zip: <%= address.zip_code %></p>
<% end %>
<%= @student.courses.each do |course| %>
<%= course.title %>
<% end %>